[package]
name = "pratyaksh_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"